version: "3"
services:
  db:
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:delegated
    ports:
      - "15432:5432"
    environment: 
      - POSTGRES_DB=${DB_DATABASE:-homestead}
      - POSTGRES_USER=${DB_USERNAME:-homestead}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - TZ=${TZ:-Asia/Tokyo}

volumes:
  db-store:
