version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${APP_PORT:-18000}:8000
    volumes:
      - ${PROJECT_PATH:-./src}:/work
      - ./docker/ash:/etc/profile.d
      - ./docker/php/psysh:/root/.config/psysh
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    env_file: .env
  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ${PROJECT_PATH:-./src}:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  db:
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:delegated
    ports:
      - "15432:5432"
    environment: 
      - POSTGRES_DB=${DB_DATABASE:-homestead}
      - POSTGRES_USER=${DB_USERNAME:-homestead}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - TZ=${TZ:-Asia/Tokyo}
volumes:
  db-store: